In [5]:
import numpy as np
# this creates a s 3-d array. You can identifiy by the number of sqaure brackets
a = np.array([[[1,2],[3,4]]])
print(f"The numpy array is {a}")
print(f"The shape of the array is {a.shape}")
print(f"The num dimensions in array is {a.ndim}")
print(f"The data type is {a.dtype}")
print(f"The num of elements  is {a.size}")
print(f"The byte size is {a.itemsize}")

The numpy array is [[[1 2]
  [3 4]]]
The shape of the array is (1, 2, 2)
The num dimensions in array is 3
The data type is int64
The num of elements  is 4
The byte size is 8


Numpy is core library for scientific computations, n-d array is the integral cahrarcteristic of numpy.
Applications include deeplearing, datascience. scikit-learn and matlaplotlib and pandas are based of this. The code is fast since it is C based.

In [17]:
# referencing a numpy array
print(a[0])
print(a[0,1])
print(a[:,1])#slicing
print(a[:,-2])#negative indexing
print(a[0,1,1])

[[1 2]
 [3 4]]
[3 4]
[[3 4]]
[[1 2]]
4


Numpy does elementwise operations. It is faster that python list. numpy also does broadcasting.


In [25]:
import time
n1 = np.random.randn(1000)
n2 = np.random.randn(1000)
print(f"Shape of the n1 {n1.shape}")
l1 = list(n1)
l2 = list(n2)
dot=0
startlist = time.time()
for i in range(len(l1)):
    dot+=l1[i]*l2[i]
endlist = time.time()
print(f"Time elapsed for dot operation of lists {startlist-endlist}")

startnumpy =time.time()
dotNumpy = np.dot(n1,n2)
endnumpy = time.time()
print(f"Time elapsed for dot operation of numpy {startnumpy-endnumpy}")


Shape of the n1 (1000,)
Time elapsed for dot operation of lists -0.00042438507080078125
Time elapsed for dot operation of numpy -9.322166442871094e-05


In [38]:
#boolean indexing
l = np.array([[1,2],[3,4],[5,6]])
b=l>2
print(b)
print(l[l>2])

#where method
print(np.where(l>2,l,-1))
l2 = np.array([10,19,30,41])

#FANCY INDEXING
b = [2,3]
print(l2[2:])



[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]
[30 41]
